version: 0.0
os: linux
files:
  - source: /app.js
    destination: /home/ec2-user/node-website
  - source: /package.json
    destination: /home/ec2-user/node-website
  - source: /public/
    destination: /home/ec2-user/node-website/public
  - source: /node_modules
    destination: /home/ec2-user/node-website/node_modules
  - source: /.babelrc
    destination: /home/ec2-user/node-website
  - source: /components
    destination: /home/ec2-user/node-website/components
  - source: /controllers
    destination: /home/ec2-user/node-website/controllers
  - source: /routes
    destination: /home/ec2-user/node-website/routes
  - source: /views
    destination: /home/ec2-user/node-website/views
hooks:
  AfterInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
    - location: scripts/start_server
      timeout: 300
      runas: root
  ApplicationStop:
    - location: scripts/stop_server
      timeout: 300
      runas: root
