const json = {

    en0: [{
        title: 'The best day',
        title2: 'of your life starts here!',
        desc: 'More than 25 years of experience making dreams come true!'
    }],
    es0: [{
        title: '¡El mejor día',
        title2: ' de tu vida comienza aquí!',
        desc: '¡Más de 25 años de experiencia haciendo realidad los sueños!'
    }],
    en1: [{
        title: 'What will you be celebrating?',
        say_i_do: 'Wedding',
        say_i_do_val: 'Saying "I do"',
        honeymoon: 'Honeymoon',
        honeymoon_val: 'Honeymoon',
        anniversary: "Anniversary",
        anniversary_val: "Anniversary",
        vow_renewal: "Vow Renewal",
        vow_renewal_val: "Vow Renewal",
    }],
    es1: [{
        title: '¿Cuál de las siguientes opciones describe mejor tu celebración?',
        say_i_do: "Boda", //'Diciendo "Sí, quiero"',
        say_i_do_val: 'Saying "I do"',
        honeymoon: 'Luna de miel',
        honeymoon_val: 'Honeymoon',
        anniversary: "Aniversario",
        anniversary_val: "Anniversary",
        vow_renewal: "Renovación de votos",
        vow_renewal_val: "Vow Renewal",
    }],
    en2: [{
        title: "Tell us more about yourself. <br />You are...",
        bride: "The Beautiful Bride",
        bride_val: "The Beautiful Bride",
        groom: "The Lucky Groom",
        groom_val: "The Lucky Groom",
        parent: "Proud Parent",
        parent_val: "Proud Parent",
        friend: "Helpful Friend/Planner/Travel Advisor",
        friend_val: "Helpful Friend/Planner/Travel Advisor",
        form_name: "What's your name?*",
        form_country: "Your country/state of residence *",
        form_place_name: "First Name",
        form_place_lastname: "Last Name",
        form_place_country: "Select your country",
        form_place_state: "Select your state",

    }],
    es2: [{
        title: "Cuéntanos más sobre ti. <br /> Eres ...",
        bride: "La hermosa novia",
        bride_val: "The Beautiful Bride",
        groom: "El novio afortunado",
        groom_val: "The Lucky Groom",
        parent: "Padre orgulloso",
        parent_val: "Proud Parent",
        friend: "Amiga/Planificadora/Asesor de Viajes",
        friend_val: "Helpful Friend/Planner/Travel Advisor",
        form_name: "¿Cuál es tu nombre?*",
        form_country: "Su país / estado de residencia *",
        form_place_name: "Primer Nombre",
        form_place_lastname: "Apellido",
        form_place_country: "Selecciona Tu País",
        form_place_state: "Selecciona Tu Estado",
    }],
    en3: [{
        title: "Tell us more about your spouse",
        titleBride: "Tell us more about the bride",
        titleCouple: "Tell us more about the couple",
        groom: "Groom's Full name*",
        bride: "Bride Full name*",
        form_place_name: "First Name",
        form_place_lastname: "Last name",

    }],
    es3: [{
        title: "Cuéntanos más sobre tu pareja",
        titleBride: "Cuéntanos más sobre la novia",
        titleCouple: "Cuéntanos más sobre la pareja",
        groom: "Nombre completo del novio *",
        bride: "Nombre completo de la novia*",
        form_place_name: "Nombre(s)",
        form_place_lastname: "Apellidos",

    }],
    en4: [{
        title: "When is your celebration?",
        exact_date: " I know the exact date",
        season: "I have a season in mind",
        deciding: "I'm still deciding",
        many_guest: "How many guests will you invite?",
        number_guest: "Enter the number of guests",
        not_sure: "I'm not sure",
        guests: "guests",
        seasons: ["Winter 2020-21", "Spring 2021", "Summer 2021", "Fall 2021", "Winter 2021-22", "Spring 2022", "Summer 2022", "Fall 2022", "Winter 2022-23", "Spring 2023"],
        place_holder: "Season in mind",
        place_holder_date: "Select wedding date"
    }],
    es4: [{
        title: "¿Cuándo planeas hacer tu boda o evento?",
        exact_date: "Sé la fecha exacta",
        season: "Tengo una temporada en mente",
        deciding: "Todavía estoy decidiendo",
        many_guest: "¿Cuántas personas asistirán a tu boda?",
        number_guest: "Ingrese el número de invitados",
        not_sure: "No estoy segura",
        guests: "invitados",
        seasons: ["Primavera 2020-21", "Verano 2021", "Otoño 2021", "Invierno 2021", "Primavera 2021-22", "Verano 2022", "Otoño 2022", "Invierno 2022", "Primavera 2022-23", "Verano 2023"],
        place_holder: "Temporada en mente",
        place_holder_date: "Selecciona fecha de boda"
    }],
    en5: [{
        title: "Where do  you want to go?",
        title_resorts: "Select as many as you'd like",
        title_resorts2: "Select one resort",
        not_sure: "I'm not sure",
        title_did: " Did someone refer you to Palace Resorts?",
        title_cert: "Would you like to work with a particular wedding planner?",
        title_tell_us: "How do we get in touch with you?",
        title_agency: "Are you a travel agent requesting this for a client?",
        your_mail: "What’s your email address?*",
        label_mail: "Email Address",
        label_mail_confirm: "Confirm Email Address",
        your_phone: "What's your phone number?*",
        label_your_phone: "333-333-3333",
        text: "Once you submit your profile, a Palace Resorts wedding specialist will reach out to you via email to help you select the perfect location for your destination wedding and begin planning your celebration",
        terms: "I have read and agree to the <a href='https://www.palaceresorts.com/en/terms-of-use'  target='_blank'>Terms & Conditions</a> and <a href='https://www.palaceresorts.com/en/general-privacy-notice-marketing-and-advertising'  target='_blank'>Privacy Notice.</a>*",
        text2: " Your personal information will not be shared with any third parties. By submitting your profile, you consent to receive relevant email correspondence and text messages from Palace Resorts Weddings to assist you in planning your event, with the option to unsubscribe at any time",
        specialist: "Wedding Planner's Full's Name*",
        agency_name: "Name of Travel agency",
        agency_iata: "IATA",
        form_country: "Your country/state of residence *",
        form_place_country: "Select your Country",
        form_place_state: "Select your State",
        agency_address: "Where are you located?",
        agency_address_address: "Travel Agency Address",
        agency_addres_phone: "Travel Agency Phone Number",
        agency_city: "Travel Agency City",
        agency_zip: "Travel Agency ZIP Code",
        place_holder: "Select the preview paradise event",
        //seasons: ["July 30, 2021 - Moon Palace Cancun", "September 24, 2021 - Moon Palace Cancun", "December 3, 2021 - Moon Palace Cancun"],//"May 28, 2021 - Moon Palace Cancun",
        seasons: [
            // "September 24, 2021 - Moon Palace Cancun",
            "December 3, 2021 - Moon Palace Cancun",
            "January 28, 2022 - Moon Palace Cancun",
            "February 25, 2022 - Moon Palace Cancun",
            "March 25, 2022 - Moon Palace Cancun",
            "April 29, 2022 - Moon Palace Cancun",
            "May 27, 2022 - Moon Palace Cancun",
            "June 24, 2022 - Moon Palace Cancun",
            "July 29, 2022 - Moon Palace Cancun",
            "August 26, 2022 - Moon Palace Cancun",
            "September 30, 2022 - Moon Palace Cancun",
            "October 28, 2022 - Moon Palace Cancun",
            "December 2, 2022 - Moon Palace Cancun",
        ],//"May 28, 2021 - Moon Palace Cancun",
        member: "Are you a Palace Elite member?", //"Are you a member of Palace Resorts?",
        member_booking: "I’m booking through a Palace Elite member" //"I'm booking through a member"
    }],
    es5: [{
        title: "¿A dónde quieres ir?",
        title_resorts: "¿Cuál destino te interesa? (Selecciona todos los que quieras)",
        title_resorts2: "Select one resort",
        not_sure: "No estoy segura",
        title_did: "¿Alguien te refirió nuestros servicios?",
        title_cert: "¿Tienes un coordinador de bodas certificado con el que quieres trabajar?", //"¿Tiene un especialista en bodas certificado con el que le gustaría trabajar?",
        title_tell_us: "Dinos como te podemos contactar para organizar tu boda. ", //"¡Díganos cómo podemos comunicarnos con usted para planificar su celebración!",
        title_agency: "¿Eres un agente de viajes que solicita esto para un cliente?",
        your_mail: "¿Cuál es tu dirección de correo electrónico?*",
        label_mail: "Email", //"Tu correo electrónico @",
        label_mail_confirm: "Confirma tu email", //"Confirm Tu correo electrónico",
        your_phone: "¿Cuál es tu número de teléfono?*",
        label_your_phone: "Teléfono",
        text: "Una vez que envíes tu perfil, este será asignado a un coordinador de bodas en el destino seleccionado. Tu coordinador se comunicará contigo por Email para ayudarte a seleccionar el lugar ideal para hacer sus sueños realidad.", //"Una vez que envíe su perfil, se le asignará un especialista certificado en bodas de Palace Resorts en función de su destino y detalles del evento. Luego, su especialista se comunicará con usted por correo electrónico para ayudarlo a seleccionar el lugar perfecto para su boda de destino y comenzar el proceso de planificación.",
        terms: "He leído y acepto los <a href='https://www.palaceresorts.com/es/terminos-y-condiciones' target='_blank'> Términos y condiciones </a> y <a href='https://www.palaceresorts.com/es/usuarios' target='_blank'> Aviso de privacidad </a> *",
        text2: "Su información personal no será compartida con terceros. Al enviar su perfil, usted acepta recibir correspondencia por correo electrónico relevante y mensajes de texto de Palace Resorts Weddings para ayudarlo a planificar su evento, con la opción de darse de baja en cualquier momento",
        specialist: "Nombre completo del especialista",
        agency_name: "Nombre de la agencia de viajes.",
        agency_iata: "IATA",
        form_country: "Su país / estado de residencia *",
        form_place_country: "País", //"Selecciona Tu País",
        form_place_state: "Estado", //"Selecciona Tu Estado",
        agency_address: "¿Cuál es la dirección de tu agencia?",
        agency_address_address: "Dirección", // de la agencia
        agency_addres_phone: "Teléfono", //Número de teléfono de la agencia
        agency_city: "Ciudad de la Agencia de Viajes ",
        agency_zip: "C.P. de la agencia de Viajes",
        place_holder: " Seleccione una opción",
        seasons: [
            // "Julio 30, 2021 - Moon Palace Cancun",
            // "Septiembre 24, 2021 - Moon Palace Cancun",
            "Diciembre 3, 2021 - Moon Palace Cancun",
            "Enero 28, 2022 - Moon Palace Cancun",
            "Febrero 25, 2022 - Moon Palace Cancun",
            "Marzo 25, 2022 - Moon Palace Cancun",
            "Abril 29, 2022 - Moon Palace Cancun",
            "Mayo 27, 2022 - Moon Palace Cancun",
            "Junio 24, 2022 - Moon Palace Cancun",
            "Julio 29, 2022 - Moon Palace Cancun",
            "Agosto 26, 2022 - Moon Palace Cancun",
            "Septiembre 30, 2022 - Moon Palace Cancun",
            "Octubre 28, 2022 - Moon Palace Cancun",
            "Deciembre 2, 2022 - Moon Palace Cancun",
        ],//"Mayo 28, 2021 - Moon Palace Cancun",
        member: "¿Eres Socio Palace Elite (Club Vacacional)?", //"Eres miembro de Palace Resorts?",
        member_booking: "Estoy reservando por medio de un socio Palace Elite", //"Estoy reservando a través de un miembro"
    }],


}

export default json;
