const json = {
	en:{
	    sliderStep:[
		   {
				imageDesk:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/Planning/step-by-step-desktop.jpg",
				imageMov:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/Planning/step-by-step-mobile.jpg",
				title:"",
				title2:"",
				description:"",
				buttonTxt:"",
				urlBtn:"",
			},
		],
		stepbystep:{
			title:"For lasting memories, <span>first things first</span>",
			subtitle:"",
			description:"Make your destination wedding perfect. Follow these steps, and you’re on the right track to a flawless best day ever.",
			steps:[
				{
					title:"We’re Getting <span>Married!</span>",
					subtitle:"",
					description: "Share the great news of your engagement with family and friends.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/engagement-ring.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/engagement-ring.png",
					text: "",
					order: 1,
					imgClass:"ring",
					flechamobile:""
				},
				{
					title:"First, <span> Let’s Celebrate! </span>",
					subtitle:"",
					description: "Hold a low-pressure, fun engagement party to kick off your festivities. Set a date and make your guestlist.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/party-invitations.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/party-invitations.png",
					text: "",
					order: 2,
					imgClass:"invitation",
					extraClass:"fadeLeft invitationCont",
					claseFlecha:"invitation-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-2.png"
				},
				{
					title:"Let’s Do <span> the Numbers </span>",
					subtitle:"",
					description: "Set a realistic wedding budget now by knowing how much you can afford and who’ll be contributing financially.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/setting-budget.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/setting-budget.png",
					text: "",
					order: 3,
					imgClass:"budget ",
					extraClass:"budgetCont",
					claseFlecha:"budget-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-3.png"
				},
				{
					title:"Who’s Coming to <span> Our Wedding?</span>",
					subtitle:" ",
					description: "Create your guestlist, starting with immediate family and friends first, and work from there.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/guest-list.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/guest-list.png",
					text: "",
					order: 4,
					imgClass:"guestList",
					extraClass:"faderight comingCont",
					claseFlecha:"guestList-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-4.png"
				},
				{
					title:"When Is Our Big Day? <span> Where Will It Be? </span>",
					subtitle:"",
					description: "Set a wedding date and choose a venue. Looking for tropical and breathtaking? Palace Resorts has just what you’re after.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/setting-date-flowers.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/setting-date-flowers.png",
					text: "",
					order: 5,
					imgClass:"flowerdate",
					extraClass:"flowerdateCont",
					claseFlecha:"flowerdate-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-5.png"
				},
				{
					title:"What’s My <span> Wedding Style?  </span>",
					subtitle:" ",
					description: "Write your ideas down and gather everything that inspires you: color swatches, magazine pages, images, videos, and more.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/bride-dress-style.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/bride-dress-style.png",
					text: "",
					order: 6,
					imgClass:"dress",
					extraClass:"fadeLeft dressCont",
					claseFlecha:"dress-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-6.png"
				},
				{
					title:"Let Me Check with <span>My Wedding Specialist.</span>",
					subtitle:"",
					description: "Contact us for ceremony date availability, guest accommodations, and other details.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/getting-ideas.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/getting-ideas.png",
					text: "",
					order: 7,
					imgClass:"ideas",					
					extraClass:"ideasCont",
					claseFlecha:"ideas-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-7.png"
				},
				{
					title:"Let’s Do This!",
					subtitle:"",
					description: "Lock in your wedding date and guest accommodations. Read your contract thoroughly, and don’t be afraid to ask questions.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/wedding-deals.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/wedding-deals.png",
					text: "",
					order: 8,
					imgClass:"deals",
					extraClass:"faderight dealsCont",
					claseFlecha:"deals-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-8.png"
				},
				{
					title:"Save the Date.</span>",
					subtitle:"",
					description: "Make it official. Contact friends and family, asking them to mark their calendars for your destination wedding in paradise.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/wedding-coordinator.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/wedding-coordinator.png",
					text: "",
					order: 9,
					imgClass:"cordination",
					extraClass:"cordinationCont",
					claseFlecha:"cordination-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-9.png"
				},
				{
					title:"I Want a Free Sneak Peek.",
					subtitle:"",
					description: "Join us for a Preview Paradise event at one of our luxury resorts. Taste menu items, tour the property, envision how your day will unfold—includes complimentary two-night stay.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/booking-wedding.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/booking-wedding.png",
					text: "",
					order: 10,
					imgClass:"book",
					extraClass:"fadeLeft freeCont",
					claseFlecha:"book-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-10.png"
				},
				
				/*{
					title:"When Is Our Big Day? <span> Where Will It Be? </span>",
					subtitle:"",
					description: "Set a wedding date and choose a venue. Looking for tropical and breathtaking? Palace Resorts has just what you’re after.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/setting-date-flowers.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/setting-date-flowers.png",
					text: "",
					order: 5,
					imgClass:"flowerdate",
					extraClass:"flowerdateCont",
					claseFlecha:"flowerdate-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-5.png"
				},
				{
					title:"What’s My <span> Wedding Style?  </span>",
					subtitle:" ",
					description: "Write your ideas down and gather everything that inspires you: color swatches, magazine pages, images, videos, and more.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/bride-dress-style.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/bride-dress-style.png",
					text: "",
					order: 6,
					imgClass:"dress",
					extraClass:"fadeLeft dressCont",
					claseFlecha:"dress-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-6.png"
				},
				{
					title:"-",
					subtitle:"",
					description: "-",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/getting-ideas.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/getting-ideas.png",
					text: "",
					order: 7,
					imgClass:"ideas",					
					extraClass:"ideasCont",
					claseFlecha:"ideas-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-7.png"
				},
				{
					title:"-",
					subtitle:"",
					description: "-",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/wedding-deals.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/wedding-deals.png",
					text: "",
					order: 8,
					imgClass:"deals",
					extraClass:"faderight dealsCont",
					claseFlecha:"deals-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-8.png"
				},
				{
					title:"Let Me Check with <span>My Wedding Coordinator</span>",
					subtitle:"",
					description: "Contact us for ceremony date availability, guest accommodations, and other details.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/wedding-coordinator.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/wedding-coordinator.png",
					text: "",
					order: 9,
					imgClass:"cordination",
					extraClass:"cordinationCont",
					claseFlecha:"cordination-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-9.png"
				},
				{
					title:"Let’s Do This!",
					subtitle:"",
					description: "Lock in your wedding date and guest accommodations. Read your contract thoroughly, and don’t be afraid to ask questions.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/booking-wedding.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/booking-wedding.png",
					text: "",
					order: 10,
					imgClass:"book",
					extraClass:"fadeLeft freeCont",
					claseFlecha:"book-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-10.png"
				},
				{
					title:"Save the Date.</span>",
					subtitle:"",
					description: "Make it official. Contact friends and family, asking them to mark their calendars for your destination wedding in paradise.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/wedding-invites.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/wedding-invites.png",
					text: "",
					order: 11,
					imgClass:"send",
					claseFlecha:"send-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-11.png"
				},
				{
					title:"I Want a Free Sneak Peek.",
					subtitle:"",
					description: "Join us for a Preview Paradise event at one of our luxury resorts. Taste menu items, tour the property, envision how your day will unfold—includes complimentary two-night stay.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/preview-location.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/preview-location.png",
					text: "",
					order: 12,
					imgClass:"location",
					extraClass:"faderight locationCont",
					claseFlecha:"location-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-12.png"
				}*/
			]
		},
	},
	es:{
		sliderStep:[
		   {
			imageDesk:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/Planning/step-by-step-desktop.jpg",
			imageMov:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/Planning/step-by-step-mobile.jpg",
				title:"",
				title2:"",
				description:"",
				buttonTxt:"",
				urlBtn:"",
			},
		],
		stepbystep:{
			title:"Primero lo primero",
			subtitle:"",
			description:"Sigue estos pasos y estarás en el camino correcto hacia el mejor día de su vida.",
			steps:[
				{
					title:"¡Me voy <span>a casar</span>!",//"Nos vamos a <span>casar!</span>",
					subtitle:"",
					description: "Comparte la gran noticia de tu compromiso con familiares y amigos.",//"Comparte la gran noticia de su compromiso con familiares y amigos.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/engagement-ring.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/engagement-ring.png",
					text: "",
					order: 1,
					imgClass:"ring",
					flechamobile:""
				},
				{
					title:"¡Primero <span>a celebrar!</span>",
					subtitle:"",
					description: "Para empezar, organiza una fiesta de compromiso. Elige una fecha y haz tu lista de invitados.",//"Organiza una fiesta de compromiso para comenzar. elige una fecha y haga su lista de invitados.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/party-invitations.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/party-invitations.png",
					text: "",
					order: 2,
					imgClass:"invitation",
					extraClass:"fadeLeft invitationCont",
					claseFlecha:"invitation-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-2.png"
				},
				{
					title:"Haz <span>números</span>",//"Hagamos <span>números.</span>",
					subtitle:"",
					description: "Establezca un presupuesto realista  es el momento de saber cuánto invertirá y quién contribuirá financieramente.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/setting-budget.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/setting-budget.png",
					text: "",
					order: 3,
					imgClass:"budget",
					extraClass:"budgetCont",
					claseFlecha:"budget-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-3.png"
				},
				{
					title:"¿Quien viene <span>a la boda?</span>",
					subtitle:"",
					description: "Crea tu lista de invitados, comenzando por familiares y amigos cercanos.",//" Creen su lista de invitados, comenzando con familiares y amigos inmediatos y trabaja desde allí.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/guest-list.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/guest-list.png",
					text: "",
					order: 4,
					imgClass:"guestList",
					extraClass:"faderight",
					claseFlecha:"guestList-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-4.png"
				},
				{
					title:"¿Cuando será el gran día? <span>¿Dónde será?</span>",
					subtitle:"",
					description: "Establece la fecha de tu boda y elige un lugar. ¿Buscas algo tropical e impresionante? Palace Resorts tiene justo lo que buscas.",//"Establezca la fecha de tu boda y elije un lugar. ¿Buscan algo tropical e impresionante? Palace Resorts tiene justo lo que buscan.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/setting-date-flowers.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/setting-date-flowers.png",
					text: "",
					order: 5,
					imgClass:"flowerdate",
					extraClass:"flowerdateCont",
					claseFlecha:"flowerdate-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-5.png"
				},
				{
					title:"¿Cuál es <span>tu estilo?</span>",//"Cuál es mi <span>estilo?</span>",
					subtitle:"",
					description: "Escribe tus ideas y reúne todo lo que te pueda inspirar: muestras de colores, páginas de revistas, imágenes, videos y más.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/bride-dress-style.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/bride-dress-style.png",
					text: "",
					order: 6,
					imgClass:"dress",
					extraClass:"fadeLeft dressCont",
					claseFlecha:"dress-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-6.png"
				},
				{
					title:"Revisa los detalles <span>con tu especialista de bodas.</span>",
					subtitle:"",
					description: " Contáctanos para conocer la disponibilidad de fechas, el alojamiento para los huéspedes y otros detalles.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/getting-ideas.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/getting-ideas.png",
					text: "",
					order: 7,
					imgClass:"ideas",
					extraClass:"ideasCont",
					claseFlecha:"ideas-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-7.png"
				},
				{
					title:"¡Empieza la diversión!",//"Hagámoslo!",
					description: "Fija la fecha de tu boda y el hospedaje para tus invitados. Lee tu contrato con atención, no tengas miedo de hacer preguntas.",//"Fija la fecha de tu boda y el alojamiento para invitados. Lea su contrato a fondo y no tengan miedo de hacer preguntas",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/wedding-deals.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/wedding-deals.png",
					text: "",
					order: 8,
					imgClass:"deals",
					extraClass:"faderight dealsCont",
					claseFlecha:"deals-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-8.png"
				},
				{
					title:"Reserva la <span>fecha.</span>",
					subtitle:"",
					description: "Háganlo oficial. Pónganse en contacto con amigos y familiares, para que reserven la fecha de su gran dia.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/wedding-coordinator.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/wedding-coordinator.png",
					text: "",
					order: 9,
					imgClass:"cordination",
					extraClass:"cordinationCont",
					claseFlecha:"cordination-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-9.png"
				},
				{
					title:"Quiero ver cómo será mi gran día.",//"Quiero una probada del paraíso gratis.",
					subtitle:"",
					description: "Acompáñanos GRATIS en el evento “una mirada al paraíso” en uno de nuestros resorts. Prueba los menús, recorre la propiedad, visualiza como será tu gran día. Incluye una estancia de dos noches en cortesía",//"Acompáñenos en el evento una mirada al paraíso en uno de nuestros resorts. Prueben los menús, recorran la propiedad, visualicen cómo será su gran día, incluye una estancia de dos noches de cortesía.",
					imageDesk: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/desktop/booking-wedding.png",
					imageMov: "https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/booking-wedding.png",
					text: "",
					order: 10,
					imgClass:"book",
					extraClass:"fadeLeft",
					claseFlecha:"book-arrow",
					flechamobile:"https://e-commercepr.s3.amazonaws.com/assets/images/planning/stepbystep/mobile/flechas/pointer-10.png"
				},
			]
		},
	}
}
export default json